[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://beta.character.ai/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build.environment]
  NODE_VERSION = "18"